In [1]:
import numpy as np

In [2]:
#random
import numpy as np

In [48]:
r=np.random.random()
r

0.3230450490512776

In [49]:
r=np.random.random((4,4))
r

array([[0.59511477, 0.31179909, 0.05618797, 0.34454794],
       [0.69394511, 0.45949392, 0.46270437, 0.56952264],
       [0.11861891, 0.29230427, 0.45009675, 0.79122324],
       [0.49460832, 0.33608772, 0.21478379, 0.31020489]])

In [50]:
r1=np.random.randn()
r1

-2.1931784771867893

In [51]:
r1=np.random.randn(3,4)
r1

array([[ 0.50877419,  0.57575975, -1.00914349, -0.06740946],
       [-0.09121981,  0.56124744, -0.1123251 ,  1.81173729],
       [-0.6876689 , -0.4850963 , -1.29351481, -1.06068006]])

In [52]:
r1=np.random.randint(1,20)
r1

13

In [53]:
r1=np.random.randint(1,20,(5,6))
r1

array([[11,  8, 10,  2,  7,  1],
       [18,  7, 13, 16,  2,  6],
       [12,  2,  7, 11,  9, 17],
       [16,  8, 16,  1, 19,  6],
       [10, 17, 11, 16,  1, 16]])

In [54]:
otp=np.random.randint(100000,999999)
otp

519623

In [55]:
print(dir(np.random))

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']


In [56]:
print(dir(np.char))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_binary_op_dispatcher', '_bytes', '_center_dispatcher', '_clean_args', '_code_dispatcher', '_count_dispatcher', '_endswith_dispatcher', '_expandtabs_dispatcher', '_get_num_chars', '_globalvar', '_join_dispatcher', '_just_dispatcher', '_len', '_mod_dispatcher', '_multiply_dispatcher', '_partition_dispatcher', '_replace_dispatcher', '_split_dispatcher', '_splitlines_dispatcher', '_startswith_dispatcher', '_strip_dispatcher', '_to_string_or_unicode_array', '_translate_dispatcher', '_unary_op_dispatcher', '_unicode', '_use_unicode', '_vec_string', '_zfill_dispatcher', 'absolute_import', 'add', 'array', 'array_function_dispatch', 'asarray', 'asbytes', 'bool_', 'capitalize', 'center', 'character', 'chararray', 'compare_chararrays', 'count', 'decode', 'division', 'encode', 'endswith', 'equal', 'expandtabs', 'find', 'functools', 'greater', 'greater_equal', 'index', 'integer', 

In [57]:
name=['RaMya','NaiNcY','RaMu','ManI']
n=np.array(name)
n

array(['RaMya', 'NaiNcY', 'RaMu', 'ManI'], dtype='<U6')

In [58]:
m=np.char.lower(name)
m

array(['ramya', 'naincy', 'ramu', 'mani'], dtype='<U6')

In [59]:
z=np.char.upper(name)
z

array(['RAMYA', 'NAINCY', 'RAMU', 'MANI'], dtype='<U6')

In [60]:
x=np.char.swapcase(name)
x

array(['rAmYA', 'nAInCy', 'rAmU', 'mANi'], dtype='<U6')

In [61]:
x=np.char.split(name)
x

array([list(['RaMya']), list(['NaiNcY']), list(['RaMu']), list(['ManI'])],
      dtype=object)

In [62]:
x=np.char.title(name)
x

array(['Ramya', 'Naincy', 'Ramu', 'Mani'], dtype='<U6')

In [63]:
s1=['python','proggraming','language']
np.char.startswith(s1,'py')

array([ True, False, False])

In [64]:
s1=['python','proggraming','language']
np.char.endswith(s1,'ge')

array([False, False,  True])

In [65]:
a=np.char.add(['phy','lang'],['ton','uage'])
a

array(['phyton', 'language'], dtype='<U8')

In [66]:
a=['mani ','honey ','naincy ','ramu ']
b=['2','3','9','5']
c=[' cse',' it',' ece',' eee']
np.char.add(np.char.add(a,b),c)

array(['mani 2 cse', 'honey 3 it', 'naincy 9 ece', 'ramu 5 eee'],
      dtype='<U12')

In [67]:
s1=['mani','naincy','ramu','vishwa']
np.sort(s1)

array(['mani', 'naincy', 'ramu', 'vishwa'], dtype='<U6')

In [68]:
np.char.capitalize(s1)

array(['Mani', 'Naincy', 'Ramu', 'Vishwa'], dtype='<U6')

In [69]:
b=np.random.randint(1,10,(4,4))
b

array([[8, 9, 5, 1],
       [6, 9, 2, 7],
       [5, 1, 2, 1],
       [5, 5, 4, 1]])

In [70]:
a=np.array([[0,2,3,7],[8,9,0,12]])
a

array([[ 0,  2,  3,  7],
       [ 8,  9,  0, 12]])

In [71]:
a.nonzero()

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([1, 2, 3, 0, 1, 3], dtype=int64))

In [72]:
a>5

array([[False, False, False,  True],
       [ True,  True, False,  True]])

In [73]:
print(a[a>5])

[ 7  8  9 12]


In [74]:
a=np.array([[6,2,],[2,1,]])
b=np.array([[4,5,],[1,2,]])
print(a+b,'\n')
print(a-b,'\n')
print(a*b,'\n')
print(a/b,'\n')
print(a%b,'\n')
print(a@b,'\n')
a.transpose()
b.transpose()

[[10  7]
 [ 3  3]] 

[[ 2 -3]
 [ 1 -1]] 

[[24 10]
 [ 2  2]] 

[[1.5 0.4]
 [2.  0.5]] 

[[2 2]
 [0 1]] 

[[26 34]
 [ 9 12]] 



array([[4, 1],
       [5, 2]])

In [3]:
#pandas
import pandas as pd

In [30]:
#create a series using list
s1=pd.Series([10,'A','python',876,54])
s1

0        10
1         A
2    python
3       876
4        54
dtype: object

In [31]:
#create a series using tuple
s1=pd.Series((10,23,'A','python'),index=['int','int','str','str'])
s1

int        10
int        23
str         A
str    python
dtype: object

In [32]:
#create a series using directory
s1=pd.Series({'a':12,'b':13,'c':14,'d':15})
s1

a    12
b    13
c    14
d    15
dtype: int64

In [33]:
b=np.array(np.random.randint(1,10,6))
print(b)
pd.Series(b)

[7 4 9 2 5 9]


0    7
1    4
2    9
3    2
4    5
5    9
dtype: int32

In [34]:
a=pd.Series(np.array([1,2,3,4]))
print(a.update(pd.Series([2,3,4,5])))
a

None


0    2
1    3
2    4
3    5
dtype: int32

In [35]:
a.add([2,3,4,5])

0     4
1     6
2     8
3    10
dtype: int64

In [36]:
a=pd.Series(np.array([91,102,34,56]))
b=pd.Series(np.array([12,98,23,76]))
print(a.append(b),'\n')
print(a.append(b,ignore_index=True))

0     91
1    102
2     34
3     56
0     12
1     98
2     23
3     76
dtype: int32 

0     91
1    102
2     34
3     56
4     12
5     98
6     23
7     76
dtype: int32


In [37]:
print(a.divide(2),'\n')
print(b.divide(3),'\n')

0    45.5
1    51.0
2    17.0
3    28.0
dtype: float64 

0     4.000000
1    32.666667
2     7.666667
3    25.333333
dtype: float64 



In [38]:
print(a.mod(3),'\n')
print(b.mod(2),'\n')

0    1
1    0
2    1
3    2
dtype: int32 

0    0
1    0
2    1
3    0
dtype: int32 



In [39]:
divmod(a,5)

(0    18
 1    20
 2     6
 3    11
 dtype: int32, 0    1
 1    2
 2    4
 3    1
 dtype: int32)

In [40]:
b=a.replace(34,78)
b

0     91
1    102
2     78
3     56
dtype: int32

In [41]:
a.diff(1)

0     NaN
1    11.0
2   -68.0
3    22.0
dtype: float64

In [42]:
a.tolist()

[91, 102, 34, 56]

In [43]:
a.cumprod()

0          91
1        9282
2      315588
3    17672928
dtype: int32

In [44]:
#prints True if there is no Nan 
a.all()

True

In [45]:
#prints True if there any number
a.any()

True

In [46]:
a.floordiv(2)

0    45
1    51
2    17
3    28
dtype: int32

In [6]:
a=pd.Series(np.array([7,8,9,3]))
print(a.update(pd.Series([2,3,4,5],)))
a

None


0    2
1    3
2    4
3    5
dtype: int32

In [8]:
print(a.add([1,3,4,5]))

0     3
1     6
2     8
3    10
dtype: int64


In [9]:
a=pd.Series(np.array([11,12,13,15]))
b=pd.Series(np.array([22,18,23,17]))
print(a.append(b),'\n')
print(a.append(b,ignore_index=True))

0    11
1    12
2    13
3    15
0    22
1    18
2    23
3    17
dtype: int32 

0    11
1    12
2    13
3    15
4    22
5    18
6    23
7    17
dtype: int32


In [12]:
print(a.mod(3),'\n')
print(b.mod(2),'\n')

0    2
1    0
2    1
3    0
dtype: int32 

0    0
1    0
2    1
3    1
dtype: int32 



In [106]:
a=pd.Series(np.array([11,12,13,15]))
print('matrix a:\n',a)
print('addition:\n',a.add([1,3,4,5]))
b=pd.Series(np.array([22,18,23,17]))
print('matrix of b:\n',b)
print('combination of matrix b in a:\n',a.append(b),'\n')#combine matrix
print('index:\n',a.append(b,ignore_index=True))#prints with index
print('updating:\n',a.update(pd.Series([2,3,4,5],)))
print('division of matrix b:\n',b.div(a),'\n')#division
print('modulus:\n',a.mod(3),'\n')#mod function
print('mod division:\n',divmod(a,5),'\n')#mod division
print('replace:\n',a.replace(11,78),'\n')#replece an element
print('difference:\n',a.diff(1),'\n')#subtrsction
print('list form:\n',a.tolist(),'\n')#coverts into list
print('commulative product:\n',a.cumprod(),'\n')#does commulative product
print('all:\n',a.all(),'\n')#prints True if there is no Nan
print('any:\n',a.any(),'\n')#prints True if there any number
print('floordivision:\n',a.floordiv(2),'\n')

matrix a:
 0    11
1    12
2    13
3    15
dtype: int32
addition:
 0    12
1    15
2    17
3    20
dtype: int64
matrix of b:
 0    22
1    18
2    23
3    17
dtype: int32
combination of matrix b in a:
 0    11
1    12
2    13
3    15
0    22
1    18
2    23
3    17
dtype: int32 

index:
 0    11
1    12
2    13
3    15
4    22
5    18
6    23
7    17
dtype: int32
updating:
 None
division of matrix b:
 0    11.00
1     6.00
2     5.75
3     3.40
dtype: float64 

modulus:
 0    2
1    0
2    1
3    2
dtype: int32 

mod division:
 (0    0
1    0
2    0
3    1
dtype: int32, 0    2
1    3
2    4
3    0
dtype: int32) 

replace:
 0    2
1    3
2    4
3    5
dtype: int32 

difference:
 0    NaN
1    1.0
2    1.0
3    1.0
dtype: float64 

list form:
 [2, 3, 4, 5] 

commulative product:
 0      2
1      6
2     24
3    120
dtype: int32 

all:
 True 

any:
 True 

floordivision:
 0    1
1    1
2    2
3    2
dtype: int32 



In [90]:
#Dataframes using pandas
import pandas as pd
a=pd.DataFrame([11,22,33,44,55])
a

0
0  11
1  22
2  33
3  44
4  55

In [4]:
d=pd.DataFrame({'Names':['mani','naincy','vishwa'],
                'subject':['DA','ML','PYTHON'],
                'college':['IIT','AEC','ACE']},
                 index=['a','b','c'])
d

Names subject college
a    mani      DA     IIT
b  naincy      ML     AEC
c  vishwa  PYTHON     ACE

In [102]:
#indexing rows
d[0:2]

Names subject college
a    mani      DA     IIT
b  naincy      ML     AEC

In [104]:
d['subject']

a        DA
b        ML
c    PYTHON
Name: subject, dtype: object

In [1]:
import pandas as pd
import numpy as np

In [12]:
x=pd.DataFrame({'empname':['mani','naincy','vishwa','satya','ramu','ravi','raju','honey','aditya','twinkle'],
               'empid':['2','3','9','5','8','7','5','1','3','5'],
               'salary':['100000','30000','75000','25000','30000','85000','90000','45000','50000','40000'],
               'designation':['CEO','tester','designer','develper','manager','receptionist','assitant','professor','designer','developer']},
              index=['1','2','3','4','5','6','7','8','9','10'])
x

empname empid  salary   designation
1      mani     2  100000           CEO
2    naincy     3   30000        tester
3    vishwa     9   75000      designer
4     satya     5   25000      develper
5      ramu     8   30000       manager
6      ravi     7   85000  receptionist
7      raju     5   90000      assitant
8     honey     1   45000     professor
9    aditya     3   50000      designer
10  twinkle     5   40000     developer

In [14]:
x['salary']

1     100000
2      30000
3      75000
4      25000
5      30000
6      85000
7      90000
8      45000
9      50000
10     40000
Name: salary, dtype: object