In [1]:
print("hello good morning")

hello good morning


In [2]:
f=23.5
type(f)

float

In [3]:
f=1234.678
int(f)

1234

In [4]:
float(99);

In [5]:
float(99)

99.0

In [6]:
s='apple'

In [7]:
s="apple"

In [8]:
s

'apple'

In [9]:
print(float(s))

ValueError: could not convert string to float: 'apple'

In [11]:
a='1234'
print(int(a))

1234


In [12]:
print(float(a))

1234.0


In [14]:
type(a)

str

In [15]:
type(s)

str

In [16]:
a=15//5
a

3

In [17]:
a=15/5
a

3.0

In [18]:
5/2

2.5

In [19]:
5//2

2

In [20]:
5%2

1

In [21]:
7%10

7

In [26]:
x=5
y=10
if x<y and x!=0:
    print(x)

5


In [28]:
x='true'
not(x)

False

In [29]:
2^3

1

In [30]:
bin(4)

'0b100'

In [31]:
hex(20)

'0x14'

In [32]:
oct(20)

'0o24'

In [33]:
int(100010001000100)

100010001000100

In [35]:
print(100010001000100,2)

100010001000100 2


In [37]:
print(int(100010001000100,2))

TypeError: int() can't convert non-string with explicit base

In [38]:
print(bin(100010001000100),2)

0b10110101111010101100100100101010110011010100100 2


In [39]:
a=79
oct_a=oct(a)
print(int(oct_a,2))

ValueError: invalid literal for int() with base 2: '0o117'

In [40]:
a=2
a

2

In [43]:
a

2

In [45]:
m=int(input('enter no of persons:'))
n=int(input('enter no of gifts:'))
f=n%m
if f==0:
    print('equally shared')
else:
    print(m-f)

enter no of persons:22
enter no of gifts:10
12


In [47]:
us='aditya'
password='aditya@123'
user=input('enter user name:')
if us==user:
    n=int(input('enter number:'))
    if n%11==0:
        p=input('enter password:')
        if p==password:
            print('login successfull')
        else:
            print('invalid password')
else:
    print('invalid username')

enter user name:aditya
enter number:121
enter password:aditya@123
login successfull


In [48]:
for i in range(10,1,-1):
    print(i,end=' ')


10 9 8 7 6 5 4 3 2 

In [49]:
for i in range(10,1,-1):
    print(i,sep=' ')

10
9
8
7
6
5
4
3
2


In [50]:
count=0
sum=0
n=int(input('enter the number:'))
for i in range(1,n+1):
      if n%i==0:
            count=count+1
            sum=sum+i
print('count=',count)
print('sum of factors=',sum)
      


enter the number:6
count= 4
sum of factors= 12


In [52]:
count=1
sum=0
n=int(input('enter the number:'))
for i in range(1,n):
    if n%i==0:
            count=count+1
            sum=sum+i
if sum==n:
    print('perfect number')
if count==1:
        print('prime number')
      

enter the number:6
perfect number


In [54]:
num=int(input("enter a number"))
c=0
s=0
for i in range(1,num+1):
    if(num%i == 0):
        c+=1
        s+=i
if(c==2 or (s-n)==n):
    if(c==2):
        print(num,"is a prime")
    else:
        print(num," is not a prime")
    if((s-n)==n):
        print(num,"is a perfect number")    
    else:
        print(num," is not a perfect number")

enter a number6
6  is not a prime
6 is a perfect number


In [55]:
n=int(input('enter number:'))
c=0
s=0
while n!=0:
    r=n%10
    s=s*10+r
    n=n//10
    c=c+1
print(s)
print(c)


    
    

enter number:121
121
3


In [56]:
n=int(input("enter a number"))
x=n
s=0
c=0
while(n>0):
    r=n%10
    s=s*10+r
    c+=1
    n=n//10
print(c)
print(s)
while(x!=0):
    r=x%10
    print(r*c,end=" ")
    x=x//10

enter a number121
3
121
3 6 3 

In [57]:
n=int(input("enter a number"))
x=n
s=0
c=0
while(n>0):
    r=n%10
    s=s*10+r
    c+=1
    n=n//10
print('reverse number:',s)
print('count:',c)
if s==x:
    print('palindrome')
else:
    print('not a palindrome')

enter a number121
reverse number: 121
count: 3
palindrome


In [58]:
s='apple'
s[::-1]

'elppa'

In [59]:
s[-1]

'e'

In [60]:
l=[2,3,42345,'aditya',98.5]
l

[2, 3, 42345, 'aditya', 98.5]

In [61]:
l[1]

3

In [62]:
l[-2]

'aditya'

In [63]:
l[0:5]

[2, 3, 42345, 'aditya', 98.5]

In [64]:
l[::-1]

[98.5, 'aditya', 42345, 3, 2]

In [65]:
l[::2]

[2, 42345, 98.5]

In [66]:
l[3][::-1]


'aytida'

In [67]:
l[-2][::-1]

'aytida'

In [69]:
l=[1,2,1,3,4,1,5,1,6,1,2,3]
a=[]
for i in l:
    if i not in a:
        a.append(i)
print(a)

[1, 2, 3, 4, 5, 6]


In [70]:
l=[1,2,1,3,4,1,5,1,6,1,2,3]
a=[]
count=0
for i in l: 
    if l.count(i) is 1:
        a.append(i)
print(a)

[4, 5, 6]


In [72]:
a={1,2,3}
print(a.remove(1))

None


In [73]:
n=input('enter name:')
d={}
for i in n:
    d.update({i:ord(i)})
print(d)
        

enter name:abcd
{'a': 97, 'b': 98, 'c': 99, 'd': 100}


In [74]:
n=input('enter name:')
d={}
for i in n:
    d.update({i:n.count(i)})
print(d)
        

enter name:aabbcdds
{'a': 2, 'b': 2, 'c': 1, 'd': 2, 's': 1}


In [75]:
n=input('enter name:')
d={}
for i in n:
    d[i]=ord(i)
print(d)

enter name:abcd
{'a': 97, 'b': 98, 'c': 99, 'd': 100}


In [76]:
n=input('enter name:')
d={}
for i in n:
    if i in d:
        d[i]=d[i]+1
    else:
        d[i]=1
print(d)

enter name:abcdds
{'a': 1, 'b': 1, 'c': 1, 'd': 2, 's': 1}


In [79]:
# numpy
pip install numpy

SyntaxError: invalid syntax (<ipython-input-79-98ea04df1fce>, line 2)

In [80]:
import numpy as np
l=[2,3,4,5]
print(l)
type(l)

[2, 3, 4, 5]


list

In [81]:
#1-d array
a=np.array([2,3,4,5])
print(a)
print(type(a))
print('dimension:',a.ndim)
print('rows and colums:',a.shape)
print('data types:',a.dtype)
print('bytes:',a.nbytes)

[2 3 4 5]
<class 'numpy.ndarray'>
dimension: 1
rows and colums: (4,)
data types: int32
bytes: 16


In [82]:
#2-d array
a=np.array([[2,3,4,5],[6,7,8,9]])
print(a)
print('type:',type(a))
print('dimension:',a.ndim)
print('rows and columns:',a.shape)
print('data typr:',a.dtype)
print('byte:',a.nbytes)
print('item size',a.itemsize)

[[2 3 4 5]
 [6 7 8 9]]
type: <class 'numpy.ndarray'>
dimension: 2
rows and columns: (2, 4)
data typr: int32
byte: 32
item size 4


In [83]:
#3-d array
a=np.array([[[1,2,9],[3,4,5],[5,6,8],[6,7,2]]])
print(a)
print('type:',type(a))
print('dimension:',a.ndim)
print('rows and colums:',a.shape)
print('data type:',a.dtype)
print('byte:',a.nbytes)
print('item size:',a.itemsize)


[[[1 2 9]
  [3 4 5]
  [5 6 8]
  [6 7 2]]]
type: <class 'numpy.ndarray'>
dimension: 3
rows and colums: (1, 4, 3)
data type: int32
byte: 48
item size: 4


In [84]:
b=np.array([[2,3,4,5],[8,7,9,10]])
print(b)

[[ 2  3  4  5]
 [ 8  7  9 10]]


In [85]:
b[:,3]

array([ 5, 10])

In [86]:
b[1,1:3]

array([7, 9])

In [87]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [88]:
c[1,0,1]

6

In [89]:
c[:,1,1]

array([4, 8])

In [90]:
#arange
m=np.arange(10)
print(m)
n=np.arange(10,20)
print(n)
l=np.arange(10,30,2)
print(l)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]


In [91]:
o=np.arange(20,40,2).reshape(5,2)
o

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38]])

In [92]:
x=np.arange(12).reshape(3,2,2,1)
x

array([[[[ 0],
         [ 1]],

        [[ 2],
         [ 3]]],


       [[[ 4],
         [ 5]],

        [[ 6],
         [ 7]]],


       [[[ 8],
         [ 9]],

        [[10],
         [11]]]])

In [93]:
x[:,1,0,0]

array([ 2,  6, 10])

In [94]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [95]:
#linspace
p=np.linspace(1,10,10)
p

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
#logspace
r=np.logspace(1,10,30)
r

array([1.00000000e+01, 2.04335972e+01, 4.17531894e+01, 8.53167852e+01,
       1.74332882e+02, 3.56224789e+02, 7.27895384e+02, 1.48735211e+03,
       3.03919538e+03, 6.21016942e+03, 1.26896100e+04, 2.59294380e+04,
       5.29831691e+04, 1.08263673e+05, 2.21221629e+05, 4.52035366e+05,
       9.23670857e+05, 1.88739182e+06, 3.85662042e+06, 7.88046282e+06,
       1.61026203e+07, 3.29034456e+07, 6.72335754e+07, 1.37382380e+08,
       2.80721620e+08, 5.73615251e+08, 1.17210230e+09, 2.39502662e+09,
       4.89390092e+09, 1.00000000e+10])

In [97]:
#zeros
z=np.zeros((4,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [98]:
v=np.zeros((4,5),dtype=int)
v

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [99]:
#ones
e=np.ones((5,4,2,3))
e

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [100]:
#full
f=np.full((3,4),12)
f

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [101]:
np.diag(f)

array([12, 12, 12])

In [102]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [103]:
np.max(c,axis=1)

array([[3, 4],
       [7, 8]])

In [104]:
np.min(c,axis=1)

array([[1, 2],
       [5, 6]])

In [105]:
np.mean(c)

4.5

In [106]:
np.vstack(c)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [107]:
np.hstack(c)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])